#!/bin/bash
# install: installation script for dotfiles.
# Author: Peter Kokot <peterkokot@gmail.com>

is_command(){
    local command="$1"
    if ! command_loc="$(type -p "$command")" || [ -z "$command_loc" ]; then
        return 1
    else
        return 0
    fi
}

# git
if (is_command "git") then
    cp ~/.dotfiles/git/gitconfig ~/.gitconfig
    cp ~/.dotfiles/git/gitignore ~/.gitignore
    echo 'git configured'
fi

# VIM
if (is_command "vim") then
    cp ~/.dotfiles/vim/vimrc ~/.vimrc
    cp -r ~/.dotfiles/vim ~/.vim
    vim +BundleInstall +qall
    echo 'Vim runtime configuration and scripts installed'
fi

# zsh
if (is_command "zsh" ) then
    cp ~/.dotfiles/zshrc ~/.zshrc
    echo '.zshrc added'
fi

# bash
if (is_command "bash") then
    cp ~/.dotfiles/bashrc ~/.bashrc
    echo '.bashrc added'
fi

# wget
if (is_command "wget") then
    cp ~/.dotfiles/wgetrc ~/.wgetrc
    echo '.wgetrc added'
fi

# screen
if (is_command "screen") then
    cp ~/.dotfiles/screenrc ~/.screenrc
    echo '.screenrc added'
fi

