#!/bin/sh

# git
cp ~/.dotfiles/gitconfig ~/.gitconfig
echo 'git configuration added'

# VIM
cp ~/.dotfiles/vim/vimrc ~/.vimrc
cp -r ~/.dotfiles/vim ~/.vim
vim +BundleInstall +qall
echo 'Vim runtime configuration and scripts installed'
