" .vimrc as part of dotfiles
" Author: Peter Kokot <peterkokot@gmail.com>
" Source: https://github.com/peterkokot/dotfiles

set nocompatible

" required by vundle to work properly
filetype off

" vundle configuration
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" vim's plugins used in this configuration
Bundle 'gmarik/vundle'
Bundle 'tpope/vim-rails'
Bundle 'altercation/vim-colors-solarized'
Bundle 'scrooloose/nerdtree'
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
Bundle 'tpope/vim-surround'
Bundle 'kien/ctrlp.vim'
Bundle 'tpope/vim-markdown'
Bundle 'evidens/vim-twig'
Bundle 'elzr/vim-json'
Bundle 'mattn/emmet-vim'
Bundle 'scrooloose/syntastic'
Bundle 'Rykka/riv.vim'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-repeat'
Bundle 'tobyS/vmustache'
Bundle 'tobyS/pdv'
Bundle 'stephpy/vim-php-cs-fixer'
Bundle 'SirVer/ultisnips'

" required by vundle to work properly
filetype plugin indent on

syntax on
if has('gui_running')
    set background=light
else
    set background=dark
endif
set t_Co=16
let g:solarized_termcolors=256

try
    colorscheme solarized
catch
    colorscheme default
endtry
  

set cursorline cursorcolumn
set incsearch
set hlsearch
set number
set showbreak=↳
set mouse=a
set guioptions-=m
set guioptions-=T
set guioptions-=r
set ruler

" Shortcut to rapidly toggle `set list`
nmap ,l :set list!
" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬

" always show status bar
set laststatus=2

" show file encoding in status bar
if has("statusline")
    set statusline=%<%f\ %h%m%r%=%{\"[\".(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\").\"]\ \"}%k\ %-14.(%l,%c%V%)\ %P
endif

set encoding=utf-8
setglobal fileencoding=utf-8
set nobomb
set termencoding=utf-8
set fileencodings=utf-8

setlocal expandtab
setlocal shiftwidth=4
setlocal softtabstop=4

set fdm=syntax
set foldlevelstart=20
set nobackup
set noswapfile

set visualbell    " don't beep
set noerrorbells  " don't beep

set pastetoggle=<F2>

" disable folding in markdown files
let g:vim_markdown_folding_disabled=1

" set highlighting for *.md, *.markdown files
au BufRead,BufNewFile *.md set filetype=markdown
au BufRead,BufNewFile *.markdown set filetype=markdown
au BufRead,BufNewFile *.mdown set filetype=markdown

" set highlightning for *.html.twig files
au BufRead,BufNewFile *.html.twig set filetype=html.twig

" set highlightning for *.json files
au BufRead,BufNewFile *.json set filetype=json


""""""""""""""""""""""""""""""""""""""""
" custom commands
""""""""""""""""""""""""""""""""""""""""

command Q q
command Wq wq
command WQ wq


""""""""""""""""""""""""""""""""""""""""
" NERDTree
""""""""""""""""""""""""""""""""""""""""

autocmd VimEnter * NERDTree
let NERDTreeShowHidden=1
autocmd VimEnter * wincmd p

autocmd WinEnter * call s:CloseIfOnlyNerdTreeLeft()

" Close all open buffers on entering a window if the only
" buffer that's left is the NERDTree buffer
function! s:CloseIfOnlyNerdTreeLeft()
    if exists("t:NERDTreeBufName")
        if bufwinnr(t:NERDTreeBufName) != -1
            if winnr("$") == 1
                q
            endif
        endif
    endif
endfunction

"""""""""""""""""""""""""""""""""""""""
" ctrlp.vim
"""""""""""""""""""""""""""""""""""""""
set runtimepath^=~/.vim/bundle/ctrlp.vim

"Highlight potentially unwanted whitespace
highlight BadWhitespace term=standout ctermbg=red guibg=red
match BadWhitespace /[^* \t]\zs\s\+$\| \+\ze\t/


""""""""""""""""""""""""""""""""""""""
" pdv
""""""""""""""""""""""""""""""""""""""

let g:pdv_template_dir = $HOME ."/.vim/bundle/pdv/templates_snip"
" PHP documenter script bound to Control-P
autocmd FileType php inoremap <C-p> <ESC>:call pdv#DocumentWithSnip()<CR>i
autocmd FileType php nnoremap <C-p> :call pdv#DocumentWithSnip()<CR>
autocmd FileType php vnoremap <C-p> :call pdv#DocumentWithSnip()<CR>


" sets the title of the window to current opened file
let &titlestring = hostname() . "[vim(" . expand("%:t") . ")]"
if &term == "screen"
    set t_ts=^[k
    set t_fs=^[\
endif
if &term == "screen" || &term == "xterm"
    set title
endif

"""""""""""""""""""""""""""""""""""""
" set tabs or spaces for certain file
" types
"""""""""""""""""""""""""""""""""""""

" xliff
autocmd FileType xlf setlocal shiftwidth=4 tabstop=4
autocmd FileType xliff setlocal shiftwidth=4 tabstop=4

" html
autocmd FileType html setlocal shiftwidth=4 tabstop=4

" twig
autocmd FileType twig setlocal shiftwidth=4 tabstop=4

" php
autocmd FileType php setlocal shiftwidth=4 tabstop=4

" ruby
autocmd FileType ruby setlocal shiftwidth=2 tabstop=2

